import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';

import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const revalidate = 1;

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          'grainy min-h-screen font-sans antialiased',
          inter.className
        )}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
